[firebase]
type = "service_account"
project_id = "museum-chatbot-e1923"
private_key_id = "b61a1b948cbbac8045090b0c8b6bf6a15e78f94e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5w1ZQ6VWvjSFE
/Vm8FwN0zYZ9jsbPzEf7xHu/235HiKn7isITJHN1Uua9/iUzkDIFoG7FipzW8h0C
Prh2m3Kwtcbt29H6EoHBNw0jrYS7kilYZoUR4FbphKeubqm0F90RrqlVlpFBXbS+
aMEah2WP35r8adtSmixsD7zRNLgN/Br0dEpBEDu5qkIltBLD5JWPPYHnbwTL9FwA
P87XMMDph9sP74aFp8UrIuIu8tRUhMFG/lxo7oo+822iBBd1flv37ZI0Y1WjLA25
xxofZ6pZpGz/WJvuxH6IzBmRizlscTkZrJnmFVYzvDk0t4k7UmxA2bIWScPP1A5d
q5vXeDGjAgMBAAECggEABx2u/El78U4gNKLZ4aUmCj7nRH8IKaSjK0dTED3pv/bB
wDOIDLCsRZXH5gZKyYdgCywioimVqXw71T6u1UhOI+vKs4jkqcY0t0CTHcdDWuYV
9F91AILOAYMF41403QO/AbLlpLQwW0cqKdMcdpYyM0k3CC1L7AWg5wDRVFhHJq3t
QrQQknBri7xawd7i6vt3zMP+kLLaviUoGyXNK4VIVxTpI5GFBY4dcDKaCoTFd3Ww
EZTh0lQ8Pru4qyE74h8VsWKfo7VPR1DMZcZhsdlDIYFpIVUYQfbm4UU1fgifvQSD
pbgMbHOoCKqYLl8VdEB5KV8PkwVK1POiMrDaGQ17rQKBgQD6QtcB45ooas/yGj6u
zoUrwlcf2x5pR1gwRhks3kSI8tsEGOqXN2m0MgEMnRpBXwfV2ByzeaFihCG7oYA4
b5h5dbewGQ2gjwaBmhq9hSwBXryscevCDpHojtn6RAhadA2rWPTc+L6iHjNnfer7
CE4dQfs3GPdA95EE/s/T4FtbFwKBgQC+BdxgBaoVIKt1FqkppOCvRTJRdUCAftvg
pRpqKTYPcZOURw0IR/UOIxbmILo9LVpMIDcfQFz0CIZmM4LMlLZvlu3wjYxdkv3b
zqDXjo/J8M5L3zwMZY9ya/DsPb6mT396JoQ6TSIJWb2N2vjUODmL8IT0bfazW8IG
8O2LtbCFVQKBgG+F27SezbLXLoWwBmD17Uh72UF77whxX65bfpqNDjONLeach+YN
LpC7e9Y4KFwbUi2MmfWs7SsuwK2RoccEjAkMWWgjMfxr4DVfDC2Kq/qMUj3yomIf
BgyBpEevi51rfC/we2YBf0pVdQjYhx+JKu5E2gNKn9yWtkxolQrRP0TPAoGAfBa9
s6LfT862yM6Uh1JZO3u3gURNa9vr4EZQ+pSQ7gLgOcswMoEzARlfAcbLd9nfBqle
9bSFPwM2KRVoTAqtHC/2j8kPqaesyVak6D77nQb44MkVoI7N3w2oFc24a0is2Wq/
nIb0PCDzTOh657MTuVPGrwwEN1orWXcJ2Ns8O8UCgYEAtL21Xop2XrBEnUZvH1GN
njJHVVA718E9+jrp2PRVjD9UGm2vp8It2DDmPQeRLskakfQbbELbVExF4kuwKwDq
16jHgtoS5KwQR1zg7ookvMGcuxSjYcVlHfLWjjMkXDLkoWjpZOWrlsqyQcztf89U
+f+JU+rp3UCZHd3xcbxCg40=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@museum-chatbot-e1923.iam.gserviceaccount.com"
client_id = "104685171791890926453"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40museum-chatbot-e1923.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

GROQ_API_KEY = "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"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USERNAME = "chsantosh2004@gmail.com"
SMTP_PASSWORD = "kzka uohw hbxg gwgi"