# Groq API Configuration
GROQ_API_KEY = "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"

# SMTP Email Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USERNAME = "chsantosh2004@gmail.com"
SMTP_PASSWORD = "kzka uohw hbxg gwgi"

# Firebase Configuration
[firebase]
type = "service_account"
project_id = "museum-chatbot-e1923"
private_key_id = "2f83f1ca583143f256f64d4411b75b96d6f75c28"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDcy4kR+waJ9WDl\\ndADBPPERniz7vE8kqOspyTQwbO0DKwznR6RvpIFRbC6SvENfI2dxKc+qx0uFDBvd\\nSx9Qlnm2C9xWEIDGOjMChNnnJRbkEwrwnKPH05hRVwtO6CVs4tM/3tdaG0TGDzJ7\\nfcMHELg208A80/Ew58efeOL/V/fZfBIv0GoB3mOXIrjCCRV2riPp64UMl9ifKEja\\nyU0W9iuEbL+4tlLJukW4lwQDHyxSYNOg0xdn8zeGRXhmBer7MrygQZBbGgtIUFzI\\nlFzAzyPGV2ElSZqZKkBLXv0Wfge6NArdNPePw3JxZK8rOkXYE1nrtLnUDTdJlZyo\\n9/W/S85dAgMBAAECggEAK1J4W6HQf6M41uyy9Td66YUKuH4TXVMTiUhkSBgnTRbW\\nWk7xUcKKaSp73Oi5o2Iz+r1EdPLTu5BLq1kBFPPhf7nGCtEEI2Dp/1WH19WsLyYZ\\nYGqrrBq1aUhV/K6KIVpELuUPhiuRi/cRZa+gY7OBIajcsFK5oWno/j5e89ET3YUg\\nSrLLeg9nUoRRL9bXAxRAFaFolKw/geKqkVicOiWafe+GBY7tKV48qDBb8AUqbgxg\\nEGignp7iJZS0d6MDM9OVNdL1WGtu/E62oKXCzS/AKm0rkSUQmv59I1gomb6eiaVJ\\nmHTiEK1E1LAjl0UfE4rLgw5p+csRqLgo2NLkUPSKNQKBgQD0hqHHhKKXphv/M51m\\n/8dgFn44cD5/hnA3izI8uFfAutg8BX2JZJGWvHvEwZPdqlS8hbgIOCsicU0dR1pB\\nh1TN4ULCcLsZym1JM2Yu37aKBmjah3ECYEECq8xazutSxSA6sn0/XINkG664KhVD\\nhgoQgHBkdouh0ChdLLEsmLgfGwKBgQDnJ9Ytz1ZoBg55m6OgaS3vAlxaZ9CI+SQe\\n2ScHZVTNvZM9vay3ylg0ON21Tee2Wqr0qz9Z+hlVHhI3PQVkPCDNuukpJb3bk/OK\\nufFzPZlCr/+bdEj2MCEzPAutVKDlVD4DiQNwqKR2iQ4DcGCqymduh+qWJHz0x32U\\n1Rej58oH5wKBgQDqRstdYyB8dvO/8G3QLyOQVjycSj425FFDhiOdtWiuCNX/u6rp\\nJeevKerTOjw3VmhVLzCA/3+kQjWF5cT9n3GKx1W1AVjhfuZyCcLPChvT5gwzwyxt\\nAFeI/ZyPLEyeQqt8UWJagIKKOVOOsxMoXJXr9YK5XjKt18e0bYtalP9jHQKBgQCQ\\nFBuCqDZyVjwVfnZJ2OVBkZYg345yod/qvm1+RaHLL3ukQyJx2FSMEFnY1Ts1RWRD\\nZq3xFltN25V9CrLenD/SG8uS0yx4vcpSUL33l5B8qZjHu35yvOMkvSuGGTbEWnLg\\n3zjesq74F0s9x4DpU4mOsnb8qLeeFu3mo7+9cQ9TRwKBgQCw9vB8GkZWo9huGlqd\\nyqnRDJeKB20AC1kt6QK7GLWD2xi3uHm+UoD0OFS/B+/XTs32T1U5yDVqbw7cnfhJ\\ntzU9/0FCvvtwXFziz5fBHU/pEGAkKo69PzFrAIkVofsoDze5caa2NzVgS01Hw6VA\\nD7Cquj+w1J2tU31WvmSKnQb/mA==\\n-----END PRIVATE KEY-----\\n"
client_email = "firebase-adminsdk-fbsvc@museum-chatbot-e1923.iam.gserviceaccount.com"
client_id = "104685171791890926453"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40museum-chatbot-e1923.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
